### PR TITLE
update meeting template

### PR DESCRIPTION
**Pull request by glass-w**

### CODE REVIEW

**Review by WinkoErades — COMMENTED** [review]
Thank you William!

**Comment by glass-w** [comment]
@WinkoErades this was meant for internal testing (in my own fork) - but it looks as if the template still imports fine into Joplin. The only issue is I can't seem to get the emojis to import from the template (even though they render fine when adding manually in the desktop app).

**Comment by WinkoErades** [comment]
It seems to work like a charm, I like it! Even renders nice on mobile phones.
IMG_6408
IMG_6409
IMG_6410

**Comment by glass-w** [comment]
Great! I've fixed the issue on my end now, glad you like it!

**Pull request merged**
